name: Greeting
# on: [push , workflow_dispatch]
on :
    - push
    - workflow_dispatch

jobs : 
    test : 
        runs-on : ubuntu-latest
        steps : 
            -   name: Get code
                run : |
                    echo "closing repo..."
                    echo "${{toJson(github)}}"
                    git clone https://github.com/${{github.repository}}/demo.git
