name: Deploy Dist
# on: [push , workflow_dispatch]
on :
    - push
    - workflow_dispatch

jobs : 
    test : 
        runs-on : ubuntu-latest
        steps :
            - name: Checkout tools repo
              uses: actions/checkout@v5
              with:
                repository: Neel-Dalwadi/React-js
