name: Deploy Dist

on:
    push:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout react-js repo
                uses: actions/checkout@v5
                with:
                    repository: Neel-Dalwadi/React-js
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}

            -   name: Build Docker image
                uses: docker/build-push-action@v2
                with:
                    run: |
                        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pokmon_react:latest ./pokemon

            -   name: Push Docker image
                uses: docker/push-action@v2
                with:
                    run: |
                        docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokmon_react:latest
