name: Deploy Dist

on:
    push:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout react-js repo
              uses: actions/checkout@v5
              with:
                  repository: Neel-Dalwadi/React-js
                  token: ${{ secrets.GH_PAT }}  

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build Docker image
              run: |
                  cd pokemon
                  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pokmon_react:latest ./pokemon

            - name: Push Docker image
              run: |
                  cd pokemon
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/pokmon_react:latest
