name: Deploy Dist

on:
    push:
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout react-js repo
                uses: actions/checkout@v5
                with:
                    repository: Neel-Dalwadi/React-js

            -   name: Login to DockerHub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME  }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD  }}

            # Build Docker image
            -   name: Build Docker image
                run: |
                    cd pokemon
                    docker build -t ${{ secrets.DOCKERHUB_USERNAME  }}/pokemon/pokmon_react:latest .

            # Push Docker image
            -   name: Push Docker image
                run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME  }}/pokemon/pokmon_react:latest
